"""add generation_records

Revision ID: 3a3b61d0b77f
Revises: 3670c7404c79
Create Date: 2026-07-17 18:50:19.587783

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a3b61d0b77f"
down_revision: Union[str, Sequence[str], None] = "c2dae7035ea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("generation_log_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=30), nullable=False),
        sa.Column("question_id", sa.String(length=100), nullable=False),
        sa.Column("params_json", sa.JSON(), nullable=False),
        sa.Column("question_json", sa.JSON(), nullable=False),
        sa.Column("image_files", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generation_log_id"],
            ["generation_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_records_user_id"), "generation_records", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_records_user_id"), table_name="generation_records")
    op.drop_table("generation_records")
    # ### end Alembic commands ###
